### ISSUE TITLE
How to configure config values for ldap settings?

### ISSUE THREAD

**Issue by igi-1w3r53n** [heimrichhannot/contao-ldap#2]
This module seems to be very interesting. Unfortunately i get an exception message in the contao backend settings every time i try to set the 'LDAP für Mitglieder aktivieren' / 'activate ldap for members' checkbox:

`Fatal error: Uncaught exception Exception with message Please fully configure your LDAP connection at first. thrown in system\modules\ldap\classes\Ldap.php on line 50` 

It turns out that the needed config values Host, Port, Binddn, Password are not set. So i defined them manually in the localconfig.php. 

Is there a way to define them correctly? Is there a menu entry or setting i overlooked?
Is there a tutorial or handout or something to configure and handle this module?

I am using contao 3.5.31 at the moment.

**Comment by Defcon0** [comment]
OK, this shouldn't be the case. But after you set these values, the Exception should be gone and you now should be able to set settings in the settings gui in Contao cms, right?

**Comment by igi-1w3r53n** [comment]
Correct, then the dialog with the ldap settings is displayed now.
Could it be that there are some intersections in the composer.json file? When i try to load the needed dependencies (composer update) i get some error messages about 'ambiguous class resolutions'.

The needed module 'contao-request' seems to be missing when i try to use the LDAP-Login module in the frontend:

`Fatal error: Class 'HeimrichHannot\Request\Request' not found in C:\xampp\htdocs\contao_demo_4\system\modules\ldap\modules\ModuleLdapLogin.php on line 11`

**Comment by Defcon0** [comment]
OK, I just fixed the Ldap exception in tl_settings and some other php 7 type related issues (release 2.0.3 -> should be available via packagist now).

Concerning Class 'HeimrichHannot\Request\Request' -> heimrichhannot/contao-request is a requirement of the latest version of contao-ldap and must hence be available. Did you install the extension via composer? In this case, the module should've been installed also.

Concerning the ambiguous class resolutions: Which are these?

**Comment by igi-1w3r53n** [comment]
I cloned the git repo into system/modules/ldap. Than i ran composer update in this folder.
He installed a lot of dependencies and the needed files are stored in 'vendor\heimrichhannot\contao-request'.

But at the end of the composer log output there a many warnings like:

`Warning: Ambiguous class resolution, "HeimrichHannot\Request\Request" was found
in both "C:/xampp/htdocs/contao_demo_4/system/modules/ldap/vendor/contao/core/system/modules/request/src/Request.php" and "C:/xampp/htdocs/contao_demo_4/system/
modules/ldap/vendor/heimrichhannot/contao-request/src/Request.php", the first wi
ll be used.`

I'm probably doing it wrong.

**Comment by Defcon0** [comment]
You're absolutely right ;-) You have to add a new entry for contao-ldap in your composer.json in the folder /composer in your contao directory. If not already done, you have to install the composer-client in your contao instance. If everything is done, run composer update in the /composer folder (which itself is created and handled by composer-client).
